### ISSUE TITLE
注册和更新用户信息的format_str有点小问题

### ISSUE THREAD

**Issue by terloo** [rongcloud/server-sdk-python#14]
user.py的22行
`'&name ={{ name }}' \`
多了个空格，导致用户名注册不上去

**Comment by jrjrmiih** [comment]
确实多空了一个格，已经改正了，谢谢您的提醒。不过按说这个空格并不会影响注册结果，会不会是其他原因导致的？如果您愿意，可以提供更多信息，比如您使用的 python 版本，执行 python -m unittest unit_test.user_unittest.UserTestCase.test_register 的结果，和 HTTP 的抓包数据。

**Comment by nonoSword08** [comment]
加了空格get的参数就识别不到了啊老哥！
user.py的45行也是这个问题，你改漏了

**Comment by terloo** [comment]
> 确实多空了一个格，已经改正了，谢谢您的提醒。不过按说这个空格并不会影响注册结果，会不会是其他原因导致的？如果您愿意，可以提供更多信息，比如您使用的 python 版本，执行 python -m unittest unit_test.user_unittest.UserTestCase.test_register 的结果，和 HTTP 的抓包数据。

加了空格get的参数就识别不到了啊老哥！
user.py的45行也是这个问题，你改漏了

**Comment by zlraymind** [comment]
感谢你的使用啊！你重新拉下 3.1.0，这次是大改，配合单元测试都能过。
直接 pip install --upgrade rc-server-sdk，或者在 github 拉源码。
